package Sintatico;

import java.util.HashMap;
import java.util.Map;

public class Gramatica {

    private Map<Integer, String[]> listRegras = new HashMap<Integer, String[]>();

    public Gramatica() {
        listRegras.put(1, new String[]{"1", "25", "47", "53", "49"});
        listRegras.put(2, new String[]{"54", "57", "59", "62", "64"});
        listRegras.put(3, new String[]{"54", "57", "59", "62", "64"});
        listRegras.put(4, new String[]{"54", "57", "59", "62", "64"});
        listRegras.put(5, new String[]{"54", "57", "59", "62", "64"});
        listRegras.put(6, new String[]{"54", "57", "59", "62", "64"});
        listRegras.put(7, new String[]{"2", "55", "47"});
        listRegras.put(8, new String[]{"null"});
        listRegras.put(9, new String[]{"null"});
        listRegras.put(10, new String[]{"null"});
        listRegras.put(11, new String[]{"null"});
        listRegras.put(12, new String[]{"25", "56"});
        listRegras.put(13, new String[]{"null"});
        listRegras.put(14, new String[]{"46", "25", "56"});
        listRegras.put(15, new String[]{"null"});
        listRegras.put(16, new String[]{"3", "25", "40", "26", "47", "58"});
        listRegras.put(17, new String[]{"null"});
        listRegras.put(18, new String[]{"null"});
        listRegras.put(19, new String[]{"null"});
        listRegras.put(20, new String[]{"null"});
        listRegras.put(21, new String[]{"null"});
        listRegras.put(22, new String[]{"null"});
        listRegras.put(23, new String[]{"25", "40", "26", "47", "58"});
        listRegras.put(24, new String[]{"4", "55", "39", "61", "47", "60"});
        listRegras.put(25, new String[]{"null"});
        listRegras.put(26, new String[]{"null"});
        listRegras.put(27, new String[]{"null"});
        listRegras.put(28, new String[]{"null"});
        listRegras.put(29, new String[]{"55", "39", "61", "47", "60"});
        listRegras.put(30, new String[]{"8"});
        listRegras.put(31, new String[]{"9", "34", "26", "50", "26", "35", "10", "8"});
        listRegras.put(32, new String[]{"5", "25", "63", "47", "53", "47", "62"});
        listRegras.put(33, new String[]{"null"});
        listRegras.put(34, new String[]{"36", "55", "39", "8", "37"});
        listRegras.put(35, new String[]{"null"});
        listRegras.put(36, new String[]{"6", "66", "65", "7"});
        listRegras.put(37, new String[]{"null"});
        listRegras.put(38, new String[]{"47", "66", "65"});
        listRegras.put(39, new String[]{"64"});
        listRegras.put(40, new String[]{"null"});
        listRegras.put(41, new String[]{"11", "25", "69"});
        listRegras.put(42, new String[]{"12", "25"});
        listRegras.put(43, new String[]{"13", "77", "14", "66", "71"});
        listRegras.put(44, new String[]{"null"});
        listRegras.put(45, new String[]{"16", "77", "17", "66"});
        listRegras.put(46, new String[]{"18", "66", "19", "77"});
        listRegras.put(47, new String[]{"null"});
        listRegras.put(48, new String[]{"20", "36", "72", "74", "37"});
        listRegras.put(49, new String[]{"21", "36", "75", "76", "37"});
        listRegras.put(50, new String[]{"25", "67"});
        listRegras.put(51, new String[]{"27", "25", "38", "77", "28", "77", "17", "66"});
        listRegras.put(52, new String[]{"29", "77", "10", "84", "7"});
        listRegras.put(53, new String[]{"null"});
        listRegras.put(54, new String[]{"68", "38", "77"});
        listRegras.put(55, new String[]{"68", "38", "77"});
        listRegras.put(56, new String[]{"39", "66"});
        listRegras.put(57, new String[]{"34", "77", "35"});
        listRegras.put(58, new String[]{"null"});
        listRegras.put(59, new String[]{"null"});
        listRegras.put(60, new String[]{"null"});
        listRegras.put(61, new String[]{"null"});
        listRegras.put(62, new String[]{"36", "77", "70", "37"});
        listRegras.put(63, new String[]{"null"});
        listRegras.put(64, new String[]{"null"});
        listRegras.put(65, new String[]{"46", "77", "70"});
        listRegras.put(66, new String[]{"null"});
        listRegras.put(67, new String[]{"15", "66"});
        listRegras.put(68, new String[]{"null"});
        listRegras.put(69, new String[]{"null"});
        listRegras.put(70, new String[]{"25", "73"});
        listRegras.put(71, new String[]{"null"});
        listRegras.put(72, new String[]{"null"});
        listRegras.put(73, new String[]{"null"});
        listRegras.put(74, new String[]{"null"});
        listRegras.put(75, new String[]{"null"});
        listRegras.put(76, new String[]{"null"});
        listRegras.put(77, new String[]{"null"});
        listRegras.put(78, new String[]{"null"});
        listRegras.put(79, new String[]{"null"});
        listRegras.put(80, new String[]{"null"});
        listRegras.put(81, new String[]{"null"});
        listRegras.put(82, new String[]{"null"});
        listRegras.put(83, new String[]{"null"});
        listRegras.put(84, new String[]{"34", "77", "35"});
        listRegras.put(85, new String[]{"null"});
        listRegras.put(86, new String[]{"null"});
        listRegras.put(87, new String[]{"null"});
        listRegras.put(88, new String[]{"null"});
        listRegras.put(89, new String[]{"null"});
        listRegras.put(90, new String[]{"null"});
        listRegras.put(91, new String[]{"null"});
        listRegras.put(92, new String[]{"null"});
        listRegras.put(93, new String[]{"null"});
        listRegras.put(94, new String[]{"null"});
        listRegras.put(95, new String[]{"null"});
        listRegras.put(96, new String[]{"46", "72", "74"});
        listRegras.put(97, new String[]{"77"});
        listRegras.put(98, new String[]{"77"});
        listRegras.put(99, new String[]{"77"});
        listRegras.put(100, new String[]{"77"});
        listRegras.put(101, new String[]{"77"});
        listRegras.put(102, new String[]{"77"});
        listRegras.put(103, new String[]{"48"});
        listRegras.put(104, new String[]{"null"});
        listRegras.put(105, new String[]{"46", "75", "76"});
        listRegras.put(106, new String[]{"79", "78"});
        listRegras.put(107, new String[]{"79", "78"});
        listRegras.put(108, new String[]{"79", "78"});
        listRegras.put(109, new String[]{"79", "78"});
        listRegras.put(110, new String[]{"79", "78"});
        listRegras.put(111, new String[]{"79", "78"});
        listRegras.put(112, new String[]{"null"});
        listRegras.put(113, new String[]{"null"});
        listRegras.put(114, new String[]{"null"});
        listRegras.put(115, new String[]{"null"});
        listRegras.put(116, new String[]{"null"});
        listRegras.put(117, new String[]{"null"});
        listRegras.put(118, new String[]{"null"});
        listRegras.put(119, new String[]{"null"});
        listRegras.put(120, new String[]{"null"});
        listRegras.put(121, new String[]{"40", "79"});
        listRegras.put(122, new String[]{"41", "79"});
        listRegras.put(123, new String[]{"42", "79"});
        listRegras.put(124, new String[]{"43", "79"});
        listRegras.put(125, new String[]{"44", "79"});
        listRegras.put(126, new String[]{"45", "79"});
        listRegras.put(127, new String[]{"null"});
        listRegras.put(128, new String[]{"null"});
        listRegras.put(129, new String[]{"81", "80"});
        listRegras.put(130, new String[]{"81", "80"});
        listRegras.put(131, new String[]{"81", "80"});
        listRegras.put(132, new String[]{"30", "81", "80"});
        listRegras.put(133, new String[]{"31", "81", "80"});
        listRegras.put(134, new String[]{"81", "80"});
        listRegras.put(135, new String[]{"null"});
        listRegras.put(136, new String[]{"null"});
        listRegras.put(137, new String[]{"null"});
        listRegras.put(138, new String[]{"null"});
        listRegras.put(139, new String[]{"null"});
        listRegras.put(140, new String[]{"null"});
        listRegras.put(141, new String[]{"22", "81", "80"});
        listRegras.put(142, new String[]{"null"});
        listRegras.put(143, new String[]{"30", "81", "80"});
        listRegras.put(144, new String[]{"31", "81", "80"});
        listRegras.put(145, new String[]{"null"});
        listRegras.put(146, new String[]{"null"});
        listRegras.put(147, new String[]{"null"});
        listRegras.put(148, new String[]{"null"});
        listRegras.put(149, new String[]{"null"});
        listRegras.put(150, new String[]{"null"});
        listRegras.put(151, new String[]{"null"});
        listRegras.put(152, new String[]{"null"});
        listRegras.put(153, new String[]{"null"});
        listRegras.put(154, new String[]{"null"});
        listRegras.put(155, new String[]{"83", "82"});
        listRegras.put(156, new String[]{"83", "82"});
        listRegras.put(157, new String[]{"83", "82"});
        listRegras.put(158, new String[]{"83", "82"});
        listRegras.put(159, new String[]{"null"});
        listRegras.put(160, new String[]{"null"});
        listRegras.put(161, new String[]{"null"});
        listRegras.put(162, new String[]{"null"});
        listRegras.put(163, new String[]{"null"});
        listRegras.put(164, new String[]{"null"});
        listRegras.put(165, new String[]{"null"});
        listRegras.put(166, new String[]{"23", "83", "82"});
        listRegras.put(167, new String[]{"null"});
        listRegras.put(168, new String[]{"null"});
        listRegras.put(169, new String[]{"null"});
        listRegras.put(170, new String[]{"32", "83", "82"});
        listRegras.put(171, new String[]{"33", "83", "82"});
        listRegras.put(172, new String[]{"null"});
        listRegras.put(173, new String[]{"null"});
        listRegras.put(174, new String[]{"null"});
        listRegras.put(175, new String[]{"null"});
        listRegras.put(176, new String[]{"null"});
        listRegras.put(177, new String[]{"null"});
        listRegras.put(178, new String[]{"null"});
        listRegras.put(179, new String[]{"null"});
        listRegras.put(180, new String[]{"null"});
        listRegras.put(181, new String[]{"null"});
        listRegras.put(182, new String[]{"24", "83"});
        listRegras.put(183, new String[]{"72"});
        listRegras.put(184, new String[]{"26"});
        listRegras.put(185, new String[]{"36", "77", "37"});
        listRegras.put(186, new String[]{"26", "86", "39", "66", "85"});
        listRegras.put(187, new String[]{"null"});
        listRegras.put(188, new String[]{"47", "84"});
        listRegras.put(189, new String[]{"null"});
        listRegras.put(190, new String[]{"46", "26", "86"});
    }

    public String[] getGramatica(int regra) {
        return listRegras.get(regra);
    }

}
