        
        

public class TabelaParsing {

    private int tabParsing[][] = new int[176][446];

    TabelaParsing() {
//        tabParsing[52][1]  = 1;
//	tabParsing[53][2]  = 1;
//	tabParsing[53][3]  = 1;
//	tabParsing[53][4] = 1;
//	tabParsing[53][5] = 1;
//	tabParsing[53][6] = 1;
//	tabParsing[54][2]" derivacao="LABEL|LID|;" />
//	tabParsing[54][3]" derivacao="NULL" />
//	tabParsing[54][4]" derivacao="NULL" />
//	tabParsing[54][5]" derivacao="NULL" />
//	tabParsing[54][6]" derivacao="NULL" />
//	tabParsing[55][25]" derivacao="IDENTIFICADOR|REPIDENT" />
//	tabParsing[56][39]" derivacao="NULL" />
//	tabParsing[56][46]" derivacao=",|IDENTIFICADOR|REPIDENT" />
//	tabParsing[56][47]" derivacao="NULL" />
//	tabParsing[57][3]" derivacao="CONST|IDENTIFICADOR|=|INTEIRO|;|LDCONST" />
//	tabParsing[57][4]" derivacao="NULL" />
//	tabParsing[57][5]" derivacao="NULL" />
//	tabParsing[57][6]" derivacao="NULL" />
//	tabParsing[58][4]" derivacao="NULL" />
//	tabParsing[58][5]" derivacao="NULL" />
//	tabParsing[58][6]" derivacao="NULL" />
//	tabParsing[58][25]" derivacao="IDENTIFICADOR|=|INTEIRO|;|LDCONST" />
//	tabParsing[59][4]" derivacao="VAR|LID|:|TIPO|;|LDVAR" />
//	tabParsing[59][5]" derivacao="NULL" />
//	tabParsing[59][6]" derivacao="NULL" />
//	tabParsing[60][5]" derivacao="NULL" />
//	tabParsing[60][6]" derivacao="NULL" />
//	tabParsing[60][25]" derivacao="LID|:|TIPO|;|LDVAR" />
//	tabParsing[61][8]" derivacao="INTEGER" />
//	tabParsing[61][9]" derivacao="ARRAY|[|INTEIRO|..|INTEIRO|]|OF|INTEGER" />
//	tabParsing[62][5]" derivacao="PROCEDURE|IDENTIFICADOR|DEFPAR|;|BLOCO|;|DCLPROC" />
//	tabParsing[62][6]" derivacao="NULL" />
//	tabParsing[63][36]" derivacao="(|LID|:|INTEGER|)" />
//	tabParsing[63][39]" derivacao="NULL" />
//	tabParsing[64][6]" derivacao="BEGIN|COMANDO|REPCOMANDO|END" />
//	tabParsing[65][7]" derivacao="NULL" />
//	tabParsing[65][47]" derivacao=";|COMANDO|REPCOMANDO" />
//	tabParsing[66][6]" derivacao="CORPO" />
//	tabParsing[66][7]" derivacao="NULL" />
//	tabParsing[66][11]" derivacao="CALL|IDENTIFICADOR|PARAMETROS" />
//	tabParsing[66][12]" derivacao="GOTO|IDENTIFICADOR" />
//	tabParsing[66][13]" derivacao="IF|EXPRESSAO|THEN|COMANDO|ELSEPARTE" />
//	tabParsing[66][15]" derivacao="NULL" />
//	tabParsing[66][16]" derivacao="WHILE|EXPRESSAO|DO|COMANDO" />
//	tabParsing[66][18]" derivacao="REPEAT|COMANDO|UNTIL|EXPRESSAO" />
//	tabParsing[66][19]" derivacao="NULL" />
//	tabParsing[66][20]" derivacao="READLN|(|VARIAVEL|REPVARIAVEL|)" />
//	tabParsing[66][21]" derivacao="WRITELN|(|ITEMSAIDA|REPITEM|)" />
//	tabParsing[66][25]" derivacao="IDENTIFICADOR|RCOMID" />
//	tabParsing[66][27]" derivacao="FOR|IDENTIFICADOR|:=|EXPRESSAO|TO|EXPRESSAO|DO|COMANDO" />
//	tabParsing[66][29]" derivacao="CASE|EXPRESSAO|OF|CONDCASE|END" />
//	tabParsing[66][47]" derivacao="NULL" />
//	tabParsing[67][34]" derivacao="RVAR|:=|EXPRESSAO" />
//	tabParsing[67][38]" derivacao="RVAR|:=|EXPRESSAO" />
//	tabParsing[67][39]" derivacao=":|COMANDO" />
//	tabParsing[68][34]" derivacao="[|EXPRESSAO|]" />
//	tabParsing[68][38]" derivacao="NULL" />
//	tabParsing[69][7]" derivacao="NULL" />
//	tabParsing[69][15]" derivacao="NULL" />
//	tabParsing[69][19]" derivacao="NULL" />
//	tabParsing[69][36]" derivacao="(|EXPRESSAO|REPPAR|)" />
//	tabParsing[69][47]" derivacao="NULL" />
//	tabParsing[70][37]" derivacao="NULL" />
//	tabParsing[70][46]" derivacao=",|EXPRESSAO|REPPAR" />
//	tabParsing[71][7]" derivacao="NULL" />
//	tabParsing[71][15]" derivacao="ELSE|COMANDO" />
//	tabParsing[71][19]" derivacao="NULL" />
//	tabParsing[71][47]" derivacao="NULL" />
//	tabParsing[72][25]" derivacao="IDENTIFICADOR|VARIAVEL1" />
//	tabParsing[73][7]" derivacao="NULL" />
//	tabParsing[73][10]" derivacao="NULL" />
//	tabParsing[73][14]" derivacao="NULL" />
//	tabParsing[73][15]" derivacao="NULL" />
//	tabParsing[73][17]" derivacao="NULL" />
//	tabParsing[73][19]" derivacao="NULL" />
//	tabParsing[73][22]" derivacao="NULL" />
//	tabParsing[73][23]" derivacao="NULL" />
//	tabParsing[73][28]" derivacao="NULL" />
//	tabParsing[73][30]" derivacao="NULL" />
//	tabParsing[73][31]" derivacao="NULL" />
//	tabParsing[73][32]" derivacao="NULL" />
//	tabParsing[73][33]" derivacao="NULL" />
//	tabParsing[73][34]" derivacao="[|EXPRESSAO|]" />
//	tabParsing[73][35]" derivacao="NULL" />
//	tabParsing[73][37]" derivacao="NULL" />
//	tabParsing[73][40]" derivacao="NULL" />
//	tabParsing[73][41]" derivacao="NULL" />
//	tabParsing[73][42]" derivacao="NULL" />
//	tabParsing[73][43]" derivacao="NULL" />
//	tabParsing[73][44]" derivacao="NULL" />
//	tabParsing[73][45]" derivacao="NULL" />
//	tabParsing[73][46]" derivacao="NULL" />
//	tabParsing[73][47]" derivacao="NULL" />
//	tabParsing[74][37]" derivacao="NULL" />
//	tabParsing[74][46]" derivacao=",|VARIAVEL|REPVARIAVEL" />
//	tabParsing[75][24]" derivacao="EXPRESSAO" />
//	tabParsing[75][25]" derivacao="EXPRESSAO" />
//	tabParsing[75][26]" derivacao="EXPRESSAO" />
//	tabParsing[75][30]" derivacao="EXPRESSAO" />
//	tabParsing[75][31]" derivacao="EXPRESSAO" />
//	tabParsing[75][36]" derivacao="EXPRESSAO" />
//	tabParsing[75][48]" derivacao="LITERAL" />
//	tabParsing[76][37]" derivacao="NULL" />
//	tabParsing[76][46]" derivacao=",|ITEMSAIDA|REPITEM" />
//	tabParsing[77][24]" derivacao="EXPSIMP|REPEXPSIMP" />
//	tabParsing[77][25]" derivacao="EXPSIMP|REPEXPSIMP" />
//	tabParsing[77][26]" derivacao="EXPSIMP|REPEXPSIMP" />
//	tabParsing[77][30]" derivacao="EXPSIMP|REPEXPSIMP" />
//	tabParsing[77][31]" derivacao="EXPSIMP|REPEXPSIMP" />
//	tabParsing[77][36]" derivacao="EXPSIMP|REPEXPSIMP" />
//	tabParsing[78][7]" derivacao="NULL" />
//	tabParsing[78][10]" derivacao="NULL" />
//	tabParsing[78][14]" derivacao="NULL" />
//	tabParsing[78][15]" derivacao="NULL" />
//	tabParsing[78][17]" derivacao="NULL" />
//	tabParsing[78][19]" derivacao="NULL" />
//	tabParsing[78][28]" derivacao="NULL" />
//	tabParsing[78][35]" derivacao="NULL" />
//	tabParsing[78][37]" derivacao="NULL" />
//	tabParsing[78][40]" derivacao="=|EXPSIMP" />
//	tabParsing[78][41]" derivacao=">|EXPSIMP" />
//	tabParsing[78][42]" derivacao=">=|EXPSIMP" />
//	tabParsing[78][43]" derivacao="&lt;|EXPSIMP" /><!-- Sinal de menor -->
//	tabParsing[78][44]" derivacao="&lt;=|EXPSIMP" /><!-- Sinal de menor ou igual -->
//	tabParsing[78][45]" derivacao="&lt;&gt;|EXPSIMP" /><!-- Sinal de diferente -->
//	tabParsing[78][46]" derivacao="NULL" />
//	tabParsing[78][47]" derivacao="NULL" />
//	tabParsing[79][24]" derivacao="TERMO|REPEXP" />
//	tabParsing[79][25]" derivacao="TERMO|REPEXP" />
//	tabParsing[79][26]" derivacao="TERMO|REPEXP" />
//	tabParsing[79][30]" derivacao="+|TERMO|REPEXP" />
//	tabParsing[79][31]" derivacao="-|TERMO|REPEXP" />
//	tabParsing[79][36]" derivacao="TERMO|REPEXP" />
//	tabParsing[80][7]" derivacao="NULL" />
//	tabParsing[80][10]" derivacao="NULL" />
//	tabParsing[80][14]" derivacao="NULL" />
//	tabParsing[80][15]" derivacao="NULL" />
//	tabParsing[80][17]" derivacao="NULL" />
//	tabParsing[80][19]" derivacao="NULL" />
//	tabParsing[80][22]" derivacao="OR|TERMO|REPEXP" />
//	tabParsing[80][28]" derivacao="NULL" />
//	tabParsing[80][30]" derivacao="+|TERMO|REPEXP" />
//	tabParsing[80][31]" derivacao="-|TERMO|REPEXP" />
//	tabParsing[80][35]" derivacao="NULL" />
//	tabParsing[80][37]" derivacao="NULL" />
//	tabParsing[80][40]" derivacao="NULL" />
//	tabParsing[80][41]" derivacao="NULL" />
//	tabParsing[80][42]" derivacao="NULL" />
//	tabParsing[80][43]" derivacao="NULL" />
//	tabParsing[80][44]" derivacao="NULL" />
//	tabParsing[80][45]" derivacao="NULL" />
//	tabParsing[80][46]" derivacao="NULL" />
//	tabParsing[80][47]" derivacao="NULL" />
//	tabParsing[81][24]" derivacao="FATOR|REPTERMO" />
//	tabParsing[81][25]" derivacao="FATOR|REPTERMO" />
//	tabParsing[81][26]" derivacao="FATOR|REPTERMO" />
//	tabParsing[81][36]" derivacao="FATOR|REPTERMO" />
//	tabParsing[82][7]" derivacao="NULL" />
//	tabParsing[82][10]" derivacao="NULL" />
//	tabParsing[82][14]" derivacao="NULL" />
//	tabParsing[82][15]" derivacao="NULL" />
//	tabParsing[82][17]" derivacao="NULL" />
//	tabParsing[82][19]" derivacao="NULL" />
//	tabParsing[82][22]" derivacao="NULL" />
//	tabParsing[82][23]" derivacao="AND|FATOR|REPTERMO" />
//	tabParsing[82][28]" derivacao="NULL" />
//	tabParsing[82][30]" derivacao="NULL" />
//	tabParsing[82][31]" derivacao="NULL" />
//	tabParsing[82][32]" derivacao="*|FATOR|REPTERMO" />
//	tabParsing[82][33]" derivacao="/|FATOR|REPTERMO" />
//	tabParsing[82][35]" derivacao="NULL" />
//	tabParsing[82][37]" derivacao="NULL" />
//	tabParsing[82][40]" derivacao="NULL" />
//	tabParsing[82][41]" derivacao="NULL" />
//	tabParsing[82][42]" derivacao="NULL" />
//	tabParsing[82][43]" derivacao="NULL" />
//	tabParsing[82][44]" derivacao="NULL" />
//	tabParsing[82][45]" derivacao="NULL" />
//	tabParsing[82][46]" derivacao="NULL" />
//	tabParsing[82][47]" derivacao="NULL" />
//	tabParsing[83][24]" derivacao="NOT|FATOR" />
//	tabParsing[83][25]" derivacao="VARIAVEL" />
//	tabParsing[83][26]" derivacao="INTEIRO" />
//	tabParsing[83][36]" derivacao="(|EXPRESSAO|)" />
//	tabParsing[84][26]" derivacao="INTEIRO|RPINTEIRO|:|COMANDO|CONTCASE" />
//	tabParsing[85][7]" derivacao="NULL" />
//	tabParsing[85][47]" derivacao=";|CONDCASE" />
//	tabParsing[86][39]" derivacao="NULL" />
//	tabParsing[86][46]" derivacao=",|INTEIRO|RPINTEIRO" />

        
        
        tabParsing[52][1] = 1;
        tabParsing[53][2] = 2;
        tabParsing[53][3] = 3;
        tabParsing[53][4] = 4;
        tabParsing[53][5] = 5;
        tabParsing[53][6] = 6;
        tabParsing[54][2] = 7;
        tabParsing[54][3] = 8;
        tabParsing[54][4] = 9;
        tabParsing[54][5] = 10;
        tabParsing[54][6] = 11;
        tabParsing[55][25] = 12;
        tabParsing[56][39] = 13;
        tabParsing[56][46] = 14;
        tabParsing[56][47] = 15;
        tabParsing[57][3] = 16;
        tabParsing[57][4] = 17;
        tabParsing[57][5] = 18;
        tabParsing[57][6] = 19;
        tabParsing[58][4] = 20;
        tabParsing[58][5] = 21;
        tabParsing[58][6] = 22;
        tabParsing[58][25] = 23;
        tabParsing[59][4] = 24;
        tabParsing[59][5] = 25;
        tabParsing[59][6] = 26;
        tabParsing[60][5] = 27;
        tabParsing[60][6] = 28;
        tabParsing[60][25] = 29;
        tabParsing[61][8] = 30;
        tabParsing[61][9] = 31;
        tabParsing[62][5] = 32;
        tabParsing[62][6] = 33;
        tabParsing[63][36] = 34;

        tabParsing[63][39] = 35;
        tabParsing[64][6] = 36;
        tabParsing[65][7] = 37;
        tabParsing[65][47] = 38;
        tabParsing[66][6] = 38;
        tabParsing[66][7] = 39;
        tabParsing[66][11] = 40;
        tabParsing[66][12] = 41;
        tabParsing[66][13] = 42;
        tabParsing[66][15] = 43;
        tabParsing[66][16] = 44;
        tabParsing[66][18] = 45;
        tabParsing[66][19] = 46;
        tabParsing[66][20] = 47;
        tabParsing[66][20] = 48;
        tabParsing[66][21] = 49;
        tabParsing[77][25] = 50;
        tabParsing[77][26] = 51;
        tabParsing[77][30] = 52;
        tabParsing[77][31] = 53;
        tabParsing[77][36] = 54;
        tabParsing[78][40] = 55;
        tabParsing[78][41] = 56;
        tabParsing[78][42] = 57;
        tabParsing[78][43] = 58;
        tabParsing[78][44] = 59;
        tabParsing[78][45] = 60;
        tabParsing[79][24] = 61;
        tabParsing[79][25] = 62;
        tabParsing[79][26] = 63;
        tabParsing[79][30] = 64;
        tabParsing[79][31] = 65;
        tabParsing[79][36] = 66;
        tabParsing[80][22] = 67;
        tabParsing[80][30] = 68;
        tabParsing[80][31] = 69;
        tabParsing[81][24] = 70;
        tabParsing[81][25] = 71;
        tabParsing[81][26] = 72;
        tabParsing[81][36] = 73;
        tabParsing[82][23] = 74;
        tabParsing[82][32] = 75;
        tabParsing[82][33] = 76;
        tabParsing[83][24] = 77;
        tabParsing[83][25] = 78;
        tabParsing[83][26] = 79;
        tabParsing[83][36] = 80;
        tabParsing[84][26] = 81;
        tabParsing[85][47] = 82;
        tabParsing[86][46] = 83;

    }

    public int regra(int x, int y) {
        int pos = tabParsing[x][y];
        return pos;
    }
}
